server:
  port: 8086

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sabor_payment}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

app:
  outbox:
    enabled: true
    poll-interval-ms: 2000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
